/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/flowers/f15.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF, OrthographicCamera } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    f15_1: THREE.Mesh;
    f15_2: THREE.Mesh;
    f15_3: THREE.Mesh;
    f15_4: THREE.Mesh;
  };
  materials: {
    ["Material.004"]: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
    ["Material.002"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/flowers/f15.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.7, 0]} rotation={[0.18, 0.83, -0.05]} scale={0}>
        <OrthographicCamera
          makeDefault={true}
          far={2000}
          near={0.1}
          // bottom={0}
          position={[30.37, 3.24, 30.16]}
          rotation={[-0.79, 0.62, 0.52]}
          zoom={30}
        />
        <ambientLight intensity={0.5} />

        <mesh
          geometry={nodes.f15_1.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          geometry={nodes.f15_2.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.f15_3.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.f15_4.geometry}
          material={materials["Material.002"]}
        />
        <axesHelper args={[5]} />
      </group>
    </group>
  );
}

// useGLTF.preload('/f15.glb')

function F15() {
  return (
    // object3D: 빈 지역 공간
    <Model />
  );
}

export default F15;
