/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/flowers/nf10.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF, OrthographicCamera } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    f10_1: THREE.Mesh;
    f10_2: THREE.Mesh;
  };
  materials: {
    bell: THREE.MeshStandardMaterial;
    stem: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/flowers/nf10.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group scale={0.17}>
        <OrthographicCamera
          makeDefault={true}
          far={2000}
          near={0.1}
          // bottom={0}
          position={[30.37, 3.24, 30.16]}
          rotation={[-0.79, 0.62, 0.52]}
          zoom={30}
        />
        <ambientLight intensity={0.5} />
        <mesh geometry={nodes.f10_1.geometry} material={materials.bell} />
        <mesh geometry={nodes.f10_2.geometry} material={materials.stem} />
        <axesHelper args={[5]} />
      </group>
    </group>
  );
}

// useGLTF.preload('/nf10.glb')

function NF10() {
  return (
    // object3D: 빈 지역 공간
    <Model />
  );
}

export default NF10;
